# @package _global_
defaults:
  - override /ds: SemanticKITTI
  - override /model: SalsaNext

project: Baseline
run_name: SalsaNext-FocalLoss
train:
  patience: 20
  batch_size: 32
  num_workers: 4
  min_epochs: 100
  loss: FocalLoss
  learning_rate: 0.01

# sbatch --output=Baseline_SemanticKITTI.out --error=Baseline_SemanticKITTI.out --gpus-per-node=1 scripts/train/train_model.batch --experiment Baseline_SemanticKITTI