# @package _global_
defaults:
  - override /ds: SemanticKITTI
  - override /model: SalsaNext

project: Loss-Comparison
run_name: SalsaNext-CrossEntropyLoss
train:
  patience: 20
  batch_size: 32
  min_epochs: 100
  loss: CrossEntropyLoss
  learning_rate: 0.01

# sbatch --output=Loss_CrossEntropy.out --error=Loss_CrossEntropy.out --gpus-per-node=1 scripts/train/train_model.batch --experiment Loss_CrossEntropy