channels:
- pytorch
- conda-forge
- omnia
- nvidia
- anaconda
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=5.1
- blas=1.0
- boost=1.73.0
- brotlipy=0.7.0
- bzip2=1.0.8
- ca-certificates=2023.01.10
- certifi=2022.12.7
- cffi=1.15.1
- cryptography=38.0.4
- cuda=11.7.1
- cuda-cccl=11.7.91
- cuda-command-line-tools=11.7.1
- cuda-compiler=11.7.1
- cuda-cudart=11.7.99
- cuda-cudart-dev=11.7.99
- cuda-cuobjdump=11.7.91
- cuda-cupti=11.7.101
- cuda-cuxxfilt=11.7.91
- cuda-demo-suite=11.8.86
- cuda-documentation=11.8.86
- cuda-driver-dev=11.7.99
- cuda-gdb=11.8.86
- cuda-libraries=11.7.1
- cuda-libraries-dev=11.7.1
- cuda-memcheck=11.8.86
- cuda-nsight=11.8.86
- cuda-nsight-compute=11.8.0
- cuda-nvcc=11.7.99
- cuda-nvdisasm=11.8.86
- cuda-nvml-dev=11.7.91
- cuda-nvprof=11.8.87
- cuda-nvprune=11.7.91
- cuda-nvrtc=11.7.99
- cuda-nvrtc-dev=11.7.99
- cuda-nvtx=11.7.91
- cuda-nvvp=11.8.87
- cuda-runtime=11.7.1
- cuda-sanitizer-api=11.8.86
- cuda-toolkit=11.7.1
- cuda-tools=11.7.1
- cuda-visual-tools=11.7.1
- eigen=3.3.7
- eigen3=3.3.7
- ffmpeg=4.2.2
- freetype=2.12.1
- gds-tools=1.4.0.31
- giflib=5.2.1
- gmp=6.2.1
- gnutls=3.6.15
- icu=58.2
- idna=3.4
- intel-openmp=2021.4.0
- jpeg=9e
- lame=3.100
- lcms2=2.12
- ld_impl_linux-64=2.38
- lerc=3.0
- libboost=1.73.0
- libcublas=11.11.3.6
- libcublas-dev=11.11.3.6
- libcufft=10.9.0.58
- libcufft-dev=10.9.0.58
- libcufile=1.4.0.31
- libcufile-dev=1.4.0.31
- libcurand=10.3.0.86
- libcurand-dev=10.3.0.86
- libcusolver=11.4.1.48
- libcusolver-dev=11.4.1.48
- libcusparse=11.7.5.86
- libcusparse-dev=11.7.5.86
- libdeflate=1.8
- libffi=3.3
- libgcc-ng=11.2.0
- libgomp=11.2.0
- libidn2=2.3.2
- libnpp=11.8.0.86
- libnpp-dev=11.8.0.86
- libnvjpeg=11.9.0.86
- libnvjpeg-dev=11.9.0.86
- libopus=1.3.1
- libpng=1.6.37
- libstdcxx-ng=11.2.0
- libtasn1=4.16.0
- libtiff=4.5.0
- libunistring=0.9.10
- libuuid=1.41.5
- libvpx=1.7.0
- libwebp=1.2.4
- libwebp-base=1.2.4
- lz4-c=1.9.4
- mkl=2021.4.0
- mkl-service=2.4.0
- mkl_fft=1.3.1
- mkl_random=1.2.2
- ncurses=6.4
- nettle=3.7.3
- nsight-compute=2022.3.0.22
- numpy=1.23.5
- numpy-base=1.23.5
- openh264=2.1.1
- openssl=1.1.1t
- pillow=9.3.0
- pip=22.3.1
- py-boost=1.73.0
- pysocks=1.7.1
- python=3.10.6
- python-devtools=0.10.0
- pytorch=1.13.0
- pytorch-cuda=11.7
- pytorch-mutex=1.0
- readline=8.2
- requests=2.28.1
- setuptools=65.6.3
- sqlite=3.40.1
- tk=8.6.12
- torchaudio=0.13.0
- torchvision=0.14.0
- typing_extensions=4.4.0
- tzdata=2022g
- urllib3=1.26.14
- x264=1!157.20191217
- xz=5.2.10
- zlib=1.2.13
- zstd=1.5.2
- pip:
  - absl-py==1.3.0
  - addict==2.4.0
  - alabaster==0.7.13
  - antlr4-python3-runtime==4.9.3
  - appdirs==1.4.4
  - astatine==0.3.2
  - astor==0.8.1
  - astpretty==3.0.0
  - astroid==2.14.2
  - asttokens==2.2.1
  - attrs==22.2.0
  - autoflake==1.7.8
  - babel==2.11.0
  - backcall==0.2.0
  - bandit==1.7.4
  - black==22.12.0
  - cachetools==5.2.0
  - charset-normalizer==2.0.4
  - click==8.1.3
  - cmake==3.25.2
  - cognitive-complexity==1.3.0
  - comm==0.1.2
  - configargparse==1.5.3
  - contourpy==1.0.6
  - coverage==6.5.0
  - cycler==0.11.0
  - cython==0.29.33
  - darglint==1.8.1
  - dash==2.7.1
  - dash-core-components==2.0.0
  - dash-html-components==2.0.0
  - dash-table==5.0.0
  - debugpy==1.6.4
  - decorator==5.1.1
  - devtools==0.10.0
  - dill==0.3.6
  - distlib==0.3.6
  - dlint==0.14.0
  - doc8==0.11.2
  - docformatter==1.5.1
  - docker-pycreds==0.4.0
  - docutils==0.17.1
  - domdf-python-tools==3.6.0
  - entrypoints==0.4
  - eradicate==2.1.0
  - exceptiongroup==1.1.0
  - executing==1.2.0
  - fastjsonschema==2.16.2
  - filelock==3.9.0
  - flake8==4.0.1
  - flake8-2020==1.6.1
  - flake8-aaa==0.13.0
  - flake8-annotations==2.9.1
  - flake8-annotations-complexity==0.0.7
  - flake8-annotations-coverage==0.0.6
  - flake8-bandit==3.0.0
  - flake8-black==0.3.6
  - flake8-blind-except==0.2.1
  - flake8-breakpoint==1.1.0
  - flake8-broken-line==0.4.0
  - flake8-bugbear==22.12.6
  - flake8-builtins==1.5.3
  - flake8-class-attributes-order==0.1.3
  - flake8-coding==1.3.2
  - flake8-cognitive-complexity==0.1.0
  - flake8-commas==2.1.0
  - flake8-comments==0.1.2
  - flake8-comprehensions==3.10.1
  - flake8-debugger==4.1.2
  - flake8-django==1.1.5
  - flake8-docstrings==1.7.0
  - flake8-encodings==0.5.0.post1
  - flake8-eradicate==1.4.0
  - flake8-executable==2.1.3
  - flake8-expression-complexity==0.0.11
  - flake8-fixme==1.1.1
  - flake8-functions==0.0.7
  - flake8-functions-names==0.4.0
  - flake8-future-annotations==0.0.5
  - flake8-helper==0.2.1
  - flake8-isort==4.2.0
  - flake8-literal==1.3.0
  - flake8-logging-format==0.9.0
  - flake8-markdown==0.3.0
  - flake8-mutable==1.2.0
  - flake8-no-pep420==2.3.0
  - flake8-noqa==1.3.0
  - flake8-pie==0.16.0
  - flake8-plugin-utils==1.3.2
  - flake8-polyfill==1.0.2
  - flake8-pyi==22.11.0
  - flake8-pylint==0.1.3
  - flake8-pytest-style==1.7.2
  - flake8-quotes==3.3.2
  - flake8-rst-docstrings==0.2.7
  - flake8-secure-coding-standard==1.4.0
  - flake8-simplify==0.19.3
  - flake8-slots==0.1.5
  - flake8-string-format==0.3.0
  - flake8-tidy-imports==4.8.0
  - flake8-typing-imports==1.12.0
  - flake8-use-fstring==1.4
  - flake8-use-pathlib==0.3.0
  - flake8-useless-assert==0.4.4
  - flake8-variables-names==0.0.5
  - flake8-warnings==0.4.0
  - flask==2.2.2
  - flit-core==3.6.0
  - fonttools==4.38.0
  - freetype-py==2.3.0
  - fvcore==0.1.5.post20221221
  - gitdb==4.0.10
  - gitpython==3.1.30
  - google-auth==2.15.0
  - google-auth-oauthlib==0.4.6
  - grpcio==1.51.1
  - h5py==3.8.0
  - hsluv==5.0.3
  - hydra-core==1.2.0
  - hypothesis==6.68.2
  - hypothesmith==0.1.9
  - imageio==2.24.0
  - imagesize==1.4.1
  - iniconfig==2.0.0
  - iopath==0.1.10
  - ipykernel==6.19.4
  - ipython==8.8.0
  - ipywidgets==8.0.4
  - isort==5.12.0
  - itsdangerous==2.1.2
  - jedi==0.18.2
  - jinja2==3.1.2
  - joblib==1.2.0
  - jsonpatch==1.32
  - jsonpointer==2.3
  - jsonschema==4.17.3
  - jupyter-client==7.4.8
  - jupyter-core==5.1.2
  - jupyterlab-flake8==0.7.1
  - jupyterlab-widgets==3.0.5
  - kitti360scripts==1.0.0
  - kiwisolver==1.4.4
  - lark-parser==0.12.0
  - laspy==2.4.0
  - lazy-object-proxy==1.9.0
  - libcst==0.4.9
  - markdown==3.4.1
  - markupsafe==2.1.1
  - matplotlib==3.6.2
  - matplotlib-inline==0.1.6
  - mccabe==0.6.1
  - mr-proper==0.0.7
  - mypy-extensions==1.0.0
  - natsort==8.2.0
  - nbformat==5.5.0
  - nest-asyncio==1.5.6
  - networkx==3.0
  - oauthlib==3.2.2
  - omegaconf==2.2.3
  - open3d==0.16.0
  - packaging==21.3
  - pandas==1.5.2
  - pandas-vet==0.2.3
  - parso==0.8.3
  - pathspec==0.9.0
  - pathtools==0.1.2
  - pbr==5.11.1
  - pep8-naming==0.12.1
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - platformdirs==2.6.2
  - plotly==5.11.0
  - pluggy==1.0.0
  - plyfile==0.7.4
  - portalocker==2.7.0
  - prompt-toolkit==3.0.36
  - protobuf==3.20.3
  - psutil==5.9.4
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - py==1.11.0
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pybetter==0.4.1
  - pycln==1.3.5
  - pycodestyle==2.8.0
  - pycparser==2.21
  - pydocstyle==6.3.0
  - pyemojify==0.2.0
  - pyflakes==2.4.0
  - pygments==2.14.0
  - pylint==2.16.2
  - pyopenssl==22.0.0
  - pyparsing==3.0.9
  - pyqt5==5.15.7
  - pyqt5-qt5==5.15.2
  - pyqt5-sip==12.11.0
  - pyqt6==6.4.0
  - pyqt6-qt6==6.4.1
  - pyqt6-sip==13.4.0
  - pyquaternion==0.9.9
  - pyrsistent==0.19.3
  - pytest==7.2.1
  - pytest-cov==3.0.0
  - pytest-sugar==0.9.6
  - python-dateutil==2.8.2
  - python-dev-tools==2022.5.27
  - pytz==2022.7
  - pyupgrade==2.38.4
  - pywavelets==1.4.1
  - pyyaml==6.0
  - pyzmq==24.0.1
  - removestar==1.3.1
  - requests-oauthlib==1.3.1
  - restructuredtext-lint==1.4.0
  - rsa==4.9
  - ruamel-yaml==0.17.21
  - ruamel-yaml-clib==0.2.7
  - scikit-image==0.19.3
  - scikit-learn==1.2.0
  - scipy==1.9.3
  - seaborn==0.12.2
  - sentry-sdk==1.14.0
  - setproctitle==1.3.2
  - six==1.16.0
  - smmap==5.0.0
  - snowballstemmer==2.2.0
  - sortedcontainers==2.4.0
  - sphinx==4.5.0
  - sphinxcontrib-applehelp==1.0.4
  - sphinxcontrib-devhelp==1.0.2
  - sphinxcontrib-htmlhelp==2.0.1
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-qthelp==1.0.3
  - sphinxcontrib-serializinghtml==1.1.5
  - ssort==0.11.6
  - stack-data==0.6.2
  - stdlib-list==0.8.0
  - stevedore==5.0.0
  - tabulate==0.9.0
  - tenacity==8.1.0
  - tensorboard==2.11.0
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.1
  - termcolor==2.2.0
  - threadpoolctl==3.1.0
  - tifffile==2022.10.10
  - tokenize-rt==4.2.1
  - toml==0.10.2
  - tomli==2.0.1
  - tomlkit==0.11.6
  - torchmetrics==0.11.0
  - torchnet==0.0.4
  - tornado==6.2
  - tox==3.28.0
  - tox-travis==0.13
  - tqdm==4.64.1
  - traitlets==5.8.0
  - typer==0.4.2
  - typing-inspect==0.8.0
  - untokenize==0.1.1
  - virtualenv==20.19.0
  - visdom==0.2.4
  - vispy==0.12.1
  - wandb==0.13.9
  - wcwidth==0.2.5
  - websocket-client==1.5.1
  - wemake-python-styleguide==0.16.1
  - werkzeug==2.2.2
  - wheel==0.37.1
  - widgetsnbextension==4.0.5
  - wrapt==1.14.1
  - yacs==0.1.8
name: ALVE-3D
