# @package _global_
defaults:
  - override /ds: SemanticKITTI
  - override /model: SalsaNext

train:
  batch_size: 32
active:
  batch_size: 128
  criterion: AverageEntropy
  selection_objects: Voxels
  select_percentage: 0.1