defaults:
  - _self_

  # Training and testing settings
  - ds: KITTI360
  - train: default
  - model: DeepLabV3
  - active: default

  # Common settings
  - path: default
  - hydra: default

  # Experiment settings
  - experiment: default

  # KITTI-360 conversion settings
  - conversion: default

option: null
action: null

# W&B settings
group: null
project: null
job_type: null
run_name: null


