defaults:
  - _self_

  # Training and testing settings
  - ds: KITTI360
  - train: default
  - model: DeepLabV3
  - active: default

  # Common settings
  - path: default
  - hydra: default

  # Launch settings
  - launch: default

  # KITTI-360 conversion settings
  - conversion: default

action: none


