defaults:
  - _self_

  # Training and testing settings
  - ds: kitti
  - test: default
  - train: default
  - model: salsa_next

  # Common settings
  - path: default
  - hydra: default

  # Configure launch
  - launch: default

action: none


