defaults:
  - _self_

  # Training and testing settings
  - ds: kitti-360
  - train: default
  - model: deeplabv3
  - active: default

  # Common settings
  - path: default
  - hydra: default

  # KITTI-360 conversion settings
  - conversion: default

action: none


