'0': 255 # "void"
'1': 1 # "dirt"
'3': 0 # "grass"
'4': 1 # "tree"
'5': 1 # "pole"
'6': 1 # "water"
'7': 0 # "sky"
'8': 1 # "vehicle"
'9': 1 # "object"
'10': 1 # "asphalt"
'12': 1 # "building"
'15': 1 # "log"
'17': 1 # "person"
'18': 1 # "fence"
'19': 0 # "bush"
'23': 0 # "concrete"
'27': 1 # "barrier"
'31': 1 # "puddle"
'33': 1 # "mud"
'34': 1 # "rubble"
