'0': 255 # "void"
'1': 0 # "dirt"
'3': 1 # "grass"
'4': 0 # "tree"
'5': 0 # "pole"
'6': 0 # "water"
'7': 1 # "sky"
'8': 0 # "vehicle"
'9': 0 # "object"
'10': 0 # "asphalt"
'12': 0 # "building"
'15': 0 # "log"
'17': 0 # "person"
'18': 0 # "fence"
'19': 1 # "bush"
'23': 0 # "concrete"
'27': 0 # "barrier"
'31': 0 # "puddle"
'33': 0 # "mud"
'34': 0 # "rubble"