0 : 255 # "unlabeled"
1 : 255 # "outlier"
10: 1 # "car"
11: 1 # "bicycle"
13: 1 # "bus"
15: 1 # "motorcycle"
16: 1 # "on-rails"
18: 1 # "truck"
20: 1 # "other-vehicle"
30: 1 # "person"
31: 1 # "bicyclist"
32: 1 # "motorcyclist"
40: 0 # "road"
44: 0 # "parking"
48: 0 # "sidewalk"
49: 0 # "other-ground"
50: 1 # "building"
51: 1 # "fence"
52: 1 # "other-structure"
60: 0 # "lane-marking"
70: 1 # "vegetation"
71: 1 # "trunk"
72: 0 # "terrain"
80: 1 # "pole"
81: 1 # "traffic-sign"
99: 1 # "other-object"
252: 1 # "moving-car"
253: 1 # "moving-bicyclist"
254: 1 # "moving-person"
255: 1 # "moving-motorcyclist"
256: 1 # "moving-on-rails"
257: 1 # "moving-bus"
258: 1 # "moving-truck"
259: 1 # "moving-other-vehicle"
