0 : 255 # "unlabeled"
1 : 255 # "outlier"
10: 0 # "car"
11: 0 # "bicycle"
13: 0 # "bus"
15: 0 # "motorcycle"
16: 0 # "on-rails"
18: 0 # "truck"
20: 0 # "other-vehicle"
30: 0 # "person"
31: 0 # "bicyclist"
32: 0 # "motorcyclist"
40: 0 # "road"
44: 0 # "parking"
48: 0 # "sidewalk"
49: 0 # "other-ground"
50: 0 # "building"
51: 0 # "fence"
52: 0 # "other-structure"
60: 0 # "lane-marking"
70: 1 # "vegetation"
71: 0 # "trunk"
72: 0 # "terrain"
80: 0 # "pole"
81: 0 # "traffic-sign"
99: 0 # "other-object"
252: 0 # "moving-car"
253: 0 # "moving-bicyclist"
254: 0 # "moving-person"
255: 0 # "moving-motorcyclist"
256: 0 # "moving-on-rails"
257: 0 # "moving-bus"
258: 0 # "moving-truck"
259: 0 # "moving-other-vehicle"
