batch_size: 128
criterion: 'AverageEntropy'
selection_objects: 'Voxels'

select_percentage: 0.5
expected_percentage_labeled: 0

model_version: 'latest'
history_version: 'latest'
selection_version: 'latest'
metric_stats_version: 'latest'
dataset_stats_version: 'latest'