#selector_type: 'average_entropy_voxels'
#random_selector_type: 'random_voxels'
#
#select_percentage: 0.5 # percentage of voxels to select
#expected_percentage_labeled: 0.5 # expected number of voxels already selected
#
## Artifacts from Weights & Biases
#model:
#  name: 'model'
#  version: 'latest'
#
#selected_voxels:
#  name: 'selected_voxels'
#  version: 'latest'



criterion: 'average_entropy'
selection_objects: 'voxels'
#selector_type: '${active.criterion}_${active.selection_objects}'
#random_selector_type: 'random_${active.selection_objects}'

select_percentage: 0.5
expected_percentage_labeled: 0.5

model:
  name: 'model_${active.criterion}_${active.selection_objects}'
  version: 'latest'

selection:
  name: 'selection_${active.criterion}_${active.selection_objects}'
  version: 'latest'

statistics:
  name: 'statistics_${active.criterion}_${active.selection_objects}'

history:
  name: 'history_${active.criterion}_${active.selection_objects}'