#selector_type: 'average_entropy_voxels'
#random_selector_type: 'random_voxels'
#
#select_percentage: 0.5 # percentage of voxels to select
#expected_percentage_labeled: 0.5 # expected number of voxels already selected
#
## Artifacts from Weights & Biases
#model:
#  name: 'model'
#  version: 'latest'
#
#selected_voxels:
#  name: 'selected_voxels'
#  version: 'latest'



criterion: 'average_entropy'
selection_object: 'voxels'
selector_type: '${active.criterion}_${active.selection_object}'
random_selector_type: 'random_${active.selection_object}'

select_percentage: 0.5
expected_percentage_labeled: 0.5

model:
  name: 'model_${active.selector_type}'
  version: 'latest'

selection:
  name: 'selection_${active.selector_type}'
  version: 'latest'

statistics:
  name: 'statistics_${active.selector_type}'

history:
  name: 'history_${active.selector_type}'