# Basic configuration
strategy: 'Entropy'
cloud_partitions: 'Voxels'

batch_size: 128
seed_percentage: 1
percentages: [ 18, 20, 22, 24 ]

# Diversity aware selection
decay_rate: 0.95
num_clusters: 250
diversity_aware: true
redal_weights: [ 1, 0.1, 0.05 ]

# Scan filter
filter_type: null
# s
# Artifacts
#model_artifact: 'aleskucera/AL-Seed/SalsaNext_KITTI360:v2'
#selection_artifact: 'aleskucera/AL-Seed/Seed_KITTI360:v3'
model_artifact: 'aleskucera/AL-Seed/SalsaNext_SemanticKITTI:v0'
selection_artifact: 'aleskucera/AL-Seed/Seed_SemanticKITTI:v0'

