selector_type: 'entropy_voxels'
random_selector_type: 'random_voxels'

select_percentage: 1 # percentage of voxels to select
percentage_labeled: 1 # expected number of voxels already selected

state_artifact: 'state'
selected_voxels_artifact: 'selected_voxels'

