# Basic configuration
strategy: 'Entropy'
cloud_partitions: 'Voxels'

batch_size: 128
select_percentage: 0.5
expected_percentage_labeled: 0

# Diversity aware selection
decay_rate: 0.95
num_clusters: 500
diversity_aware: true
redal_weights: [ 1, 0.1, 0.05 ]

# Artifacts
model: null
selection: null
model_version: 'latest'
selection_version: 'latest'

